name: "Bug report"
description: "Create a report to help us improve"
body:
  - type: markdown
    attributes:
      value: |
        #### Advisory
        - When upgrading ruTorrent you MUST clear your web browser cache. Please follow our four step procress before submitting an issue report.
        - The rtinst install script is broken and no longer maintained. Please do NOT file bug reports using this install script. See [#2482](https://github.com/Novik/ruTorrent/discussions/2482) for alternatives.
        - Remember: Professionals still make mistakes. This template is here to help you. Many of our issue reports come from Web Developers who don't follow our template.
            
        #### Clear Cache using Google Chrome
        - Step 1: Install Google Chrome.
        - Step 2: Install [Clear Cache](https://chrome.google.com/webstore/detail/clear-cache/cppjkneekbjaeellbfkmgnhonkkjfpdn) extension.
        - Step 3: Right click Clear Cache button. Go to Options. Scroll down. Change Time Period to Everything.
        - Step 4: Left click Clear Cache button. Refresh the page.
      
  - type: checkboxes
    id: checklist
    attributes:
      label: Please complete the following tasks.
      description: Check off each box when completed.
      options:
        - label: Web browser cache cleared
          required: true
        - label: Link provided to install script if applicable
          required: true
        - label: Not using broken rtinst install script
          required: true
        - label: Web browser, ruTorrent, PHP and OS version provided
          required: true

  - type: textarea
    attributes:
      label: Tell us about your environment
      description: |
        Example of preferred formatting:
        Web Browser: Google Chrome 97.0.4692.71
        ruTorrent: v4.0-beta.1 OR Master: fc9d1f0
        PHP: PHP 7.4.3
        OS: Ubuntu 20.04.3 LTS        
      placeholder: |
        Web Browser:
        ruTorrent:
        PHP:
        OS:
    validations:
      required: true
      
  - type: textarea
    attributes:
      label: Tell us how you installed ruTorrent
      description: Link to install script goes here if applicable.
    validations:
      required: true
      
  - type: textarea
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
      
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Please provide reliable steps to reproduce the problem.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: false
      
  - type: textarea
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: false
      
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the problem here
    validations:
      required: false
