name: Multiarch Docker Image Build

on:
  release:
    types: [published]
#  push:
#    branches: [ master ]
#    paths:
#      - 'src/build/**'
#  pull_request:
#    branches: [ master ]
#    paths:
#      - './.env'

env:
   BASE_IMAGE: unzel/rutorrent:builder-base
   BUILD_PLATFORMS: linux/amd64,linux/386,linux/arm64,linux/arm/v7
   TARGET_IMAGE: unzel/rutorrent
#  BASE_IMAGE: ghcr.io/${{ github.repository_owner }}/rutorrent:builder-base


jobs:
  build:
    name: Build docker images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Extract version from release tag
        shell: bash
        run: |
          version="${{ github.event.release.tag_name }}"
          clean_version="${version#v}"  # Strip leading 'v' if present
          echo "clean_version=$clean_version" >> "$GITHUB_ENV"
      # setup Docker buildx action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          driver: docker-container
          buildkitd-flags: --allow-insecure-entitlement network.host
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push base image if needed
        run: |
          if docker pull "$BASE_IMAGE" > /dev/null 2>&1; then
            echo "Base image found, using cache."
            echo "build_base=false" >> "$GITHUB_ENV"
          else
            echo "Base image not found, will build it."
            echo "build_base=true" >> "$GITHUB_ENV"
            docker buildx build --platform=${{ env.BUILD_PLATFORMS }} --target osbuild --push --tag "$BASE_IMAGE" .
          fi

      - name: Build & push the Docker images
        run: |
          docker buildx build --platform=${{ env.BUILD_PLATFORMS }} --target rutorrent_src --push \
            --tag "${{ env.TARGET_IMAGE }}:latest" \
            --tag "${{ env.TARGET_IMAGE }}:${{ env.clean_version }}" \
            --tag "ghcr.io/${{ github.repository_owner }}/${{ env.TARGET_IMAGE }}:latest" \
            --tag "ghcr.io/${{ github.repository_owner }}/${{ env.TARGET_IMAGE }}:${{ env.clean_version }}" \
          .

