<?php

// The observable result of XMLRPCProxy::process() for every branch it has:
// what it returned, what it sent, on what trust, and what it logged.
//
// Generated from the implementation, then frozen. It is not a description of
// what the proxy should do — the suite next to it covers that — it is a record
// of what it does, so that a change to how the decision is reached shows up
// here if it changes the decision.

return array(
	"off mode rejects and sends nothing" => array(
		"request" => "<?xml version=\"1.0\"?><methodCall><methodName>load.start</methodName><params><param><value><string></string></value></param><param><value><string>http://example.test/x.torrent</string></value></param></params></methodCall>",
		"mode" => "off",
		"enableLog" => true,
		"safeParams" => array(
			"d.custom1.set",
			"d.custom.set",
			"d.directory.set",
		),
		"allowLocalPaths" => false,
		"returned" => null,
		"sends" => 0,
		"trusted" => null,
		"payload" => null,
		"log" => array(
			"xmlrpc-proxy: rejected (proxy disabled)",
		),
	),
	"off mode rejects a body that is not XML" => array(
		"request" => "not xml at all",
		"mode" => "off",
		"enableLog" => true,
		"safeParams" => array(
			"d.custom1.set",
			"d.custom.set",
			"d.directory.set",
		),
		"allowLocalPaths" => false,
		"returned" => null,
		"sends" => 0,
		"trusted" => null,
		"payload" => null,
		"log" => array(
			"xmlrpc-proxy: rejected (proxy disabled)",
		),
	),
	"passthrough_unsafe forwards the body verbatim, trusted" => array(
		"request" => "<?xml version=\"1.0\"?><methodCall><methodName>execute</methodName><params><param><value><string>id</string></value></param></params></methodCall>",
		"mode" => "passthrough_unsafe",
		"enableLog" => true,
		"safeParams" => array(
			"d.custom1.set",
			"d.custom.set",
			"d.directory.set",
		),
		"allowLocalPaths" => false,
		"returned" => "SCGI-REPLY",
		"sends" => 1,
		"trusted" => true,
		"payload" => "<?xml version=\"1.0\"?><methodCall><methodName>execute</methodName><params><param><value><string>id</string></value></param></params></methodCall>",
		"log" => array(
			"xmlrpc-proxy: passthrough (UNSAFE mode)",
		),
	),
	"a body that is not XML is forwarded untrusted" => array(
		"request" => "not xml at all",
		"mode" => "sanitize",
		"enableLog" => true,
		"safeParams" => array(
			"d.custom1.set",
			"d.custom.set",
			"d.directory.set",
		),
		"allowLocalPaths" => false,
		"returned" => "SCGI-REPLY",
		"sends" => 1,
		"trusted" => false,
		"payload" => "not xml at all",
		"log" => array(
			"xmlrpc-proxy: untrusted (invalid XML)",
		),
	),
	"a methodCall with no methodName is forwarded untrusted" => array(
		"request" => "<?xml version=\"1.0\"?><methodCall><params></params></methodCall>",
		"mode" => "sanitize",
		"enableLog" => true,
		"safeParams" => array(
			"d.custom1.set",
			"d.custom.set",
			"d.directory.set",
		),
		"allowLocalPaths" => false,
		"returned" => "SCGI-REPLY",
		"sends" => 1,
		"trusted" => false,
		"payload" => "<?xml version=\"1.0\"?><methodCall><params></params></methodCall>",
		"log" => array(
			"xmlrpc-proxy: untrusted (invalid XML)",
		),
	),
	"an unknown method is forwarded untrusted" => array(
		"request" => "<?xml version=\"1.0\"?><methodCall><methodName>system.client_version</methodName><params></params></methodCall>",
		"mode" => "sanitize",
		"enableLog" => true,
		"safeParams" => array(
			"d.custom1.set",
			"d.custom.set",
			"d.directory.set",
		),
		"allowLocalPaths" => false,
		"returned" => "SCGI-REPLY",
		"sends" => 1,
		"trusted" => false,
		"payload" => "<?xml version=\"1.0\"?><methodCall><methodName>system.client_version</methodName><params></params></methodCall>",
		"log" => array(
			"xmlrpc-proxy: untrusted: system.client_version",
		),
	),
	"a newline in an unknown method name cannot forge a log line" => array(
		"request" => "<?xml version=\"1.0\"?><methodCall><methodName>system.foo\nxmlrpc-proxy: trusted: forged</methodName><params></params></methodCall>",
		"mode" => "sanitize",
		"enableLog" => true,
		"safeParams" => array(
			"d.custom1.set",
			"d.custom.set",
			"d.directory.set",
		),
		"allowLocalPaths" => false,
		"returned" => "SCGI-REPLY",
		"sends" => 1,
		"trusted" => false,
		"payload" => "<?xml version=\"1.0\"?><methodCall><methodName>system.foo\nxmlrpc-proxy: trusted: forged</methodName><params></params></methodCall>",
		"log" => array(
			"xmlrpc-proxy: untrusted: system.foo xmlrpc-proxy: trusted: forged",
		),
	),
	"load.start with an allowed command param is rebuilt and trusted" => array(
		"request" => "<?xml version=\"1.0\"?><methodCall><methodName>load.start</methodName><params><param><value><string></string></value></param><param><value><string>http://example.test/x.torrent</string></value></param><param><value><string>d.custom1.set=label</string></value></param></params></methodCall>",
		"mode" => "sanitize",
		"enableLog" => true,
		"safeParams" => array(
			"d.custom1.set",
			"d.custom.set",
			"d.directory.set",
		),
		"allowLocalPaths" => false,
		"returned" => "SCGI-REPLY",
		"sends" => 1,
		"trusted" => true,
		"payload" => "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<methodCall><methodName>load.start</methodName><params><param><value><string></string></value></param><param><value><string>http://example.test/x.torrent</string></value></param><param><value><string>d.custom1.set=\"label\"</string></value></param></params></methodCall>",
		"log" => array(
			"xmlrpc-proxy: trusted: load.start (3 params)",
		),
	),
	"load.start strips a command param that is not allowed" => array(
		"request" => "<?xml version=\"1.0\"?><methodCall><methodName>load.start</methodName><params><param><value><string></string></value></param><param><value><string>http://example.test/x.torrent</string></value></param><param><value><string>execute=evil</string></value></param></params></methodCall>",
		"mode" => "sanitize",
		"enableLog" => true,
		"safeParams" => array(
			"d.custom1.set",
			"d.custom.set",
			"d.directory.set",
		),
		"allowLocalPaths" => false,
		"returned" => "SCGI-REPLY",
		"sends" => 1,
		"trusted" => true,
		"payload" => "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<methodCall><methodName>load.start</methodName><params><param><value><string></string></value></param><param><value><string>http://example.test/x.torrent</string></value></param></params></methodCall>",
		"log" => array(
			"xmlrpc-proxy: trusted: load.start (kept 2 params, stripped: execute=evil)",
		),
	),
	"every stripped param is named in one log line" => array(
		"request" => "<?xml version=\"1.0\"?><methodCall><methodName>load.start</methodName><params><param><value><string></string></value></param><param><value><string>http://example.test/x.torrent</string></value></param><param><value><string>execute=evil</string></value></param><param><value><string>d.peers_max.set=1</string></value></param></params></methodCall>",
		"mode" => "sanitize",
		"enableLog" => true,
		"safeParams" => array(
			"d.custom1.set",
			"d.custom.set",
			"d.directory.set",
		),
		"allowLocalPaths" => false,
		"returned" => "SCGI-REPLY",
		"sends" => 1,
		"trusted" => true,
		"payload" => "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<methodCall><methodName>load.start</methodName><params><param><value><string></string></value></param><param><value><string>http://example.test/x.torrent</string></value></param></params></methodCall>",
		"log" => array(
			"xmlrpc-proxy: trusted: load.start (kept 2 params, stripped: execute=evil, d.peers_max.set=1)",
		),
	),
	"a param this side cannot rebuild forces the call untrusted" => array(
		"request" => "<?xml version=\"1.0\"?><methodCall><methodName>load.raw_start</methodName><params><param><value><int>1</int></value></param><param><value><string>http://example.test/x.torrent</string></value></param></params></methodCall>",
		"mode" => "sanitize",
		"enableLog" => true,
		"safeParams" => array(
			"d.custom1.set",
			"d.custom.set",
			"d.directory.set",
		),
		"allowLocalPaths" => false,
		"returned" => "SCGI-REPLY",
		"sends" => 1,
		"trusted" => false,
		"payload" => "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<methodCall><methodName>load.raw_start</methodName><params><param><value><int>1</int></value></param><param><value><string>http://example.test/x.torrent</string></value></param></params></methodCall>",
		"log" => array(
			"xmlrpc-proxy: untrusted (a parameter could not be rebuilt): load.raw_start (2 params)",
		),
	),
	"a base64 data param is re-emitted without its line wrapping" => array(
		"request" => "<?xml version=\"1.0\"?><methodCall><methodName>load.raw_start</methodName><params><param><value><string></string></value></param><param><value><base64>Ynl0ZXMAyGJ5dGVzAMhieXRlcwDIYnl0ZXMAyGJ5dGVzAMhieXRlcwDIYnl0ZXMAyGJ5dGVzAMg=\n</base64></value></param><param><value><string>d.custom1.set=label</string></value></param></params></methodCall>",
		"mode" => "sanitize",
		"enableLog" => true,
		"safeParams" => array(
			"d.custom1.set",
			"d.custom.set",
			"d.directory.set",
		),
		"allowLocalPaths" => false,
		"returned" => "SCGI-REPLY",
		"sends" => 1,
		"trusted" => true,
		"payload" => "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<methodCall><methodName>load.raw_start</methodName><params><param><value><string></string></value></param><param><value><base64>Ynl0ZXMAyGJ5dGVzAMhieXRlcwDIYnl0ZXMAyGJ5dGVzAMhieXRlcwDIYnl0ZXMAyGJ5dGVzAMg=</base64></value></param><param><value><string>d.custom1.set=\"label\"</string></value></param></params></methodCall>",
		"log" => array(
			"xmlrpc-proxy: trusted: load.raw_start (3 params)",
		),
	),
	"a value with no explicit string element is read the same way" => array(
		"request" => "<?xml version=\"1.0\"?><methodCall><methodName>load.start</methodName><params><param><value><string></string></value></param><param><value><string>http://example.test/x.torrent</string></value></param><param><value>d.custom1.set=label</value></param></params></methodCall>",
		"mode" => "sanitize",
		"enableLog" => true,
		"safeParams" => array(
			"d.custom1.set",
			"d.custom.set",
			"d.directory.set",
		),
		"allowLocalPaths" => false,
		"returned" => "SCGI-REPLY",
		"sends" => 1,
		"trusted" => true,
		"payload" => "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<methodCall><methodName>load.start</methodName><params><param><value><string></string></value></param><param><value><string>http://example.test/x.torrent</string></value></param><param><value><string>d.custom1.set=\"label\"</string></value></param></params></methodCall>",
		"log" => array(
			"xmlrpc-proxy: trusted: load.start (3 params)",
		),
	),
	"the 0.9.x method names take the same parameter positions" => array(
		"request" => "<?xml version=\"1.0\"?><methodCall><methodName>load_start</methodName><params><param><value><string>http://example.test/x.torrent</string></value></param><param><value><string>d.custom1.set=label</string></value></param></params></methodCall>",
		"mode" => "sanitize",
		"enableLog" => true,
		"safeParams" => array(
			"d.custom1.set",
			"d.custom.set",
			"d.directory.set",
		),
		"allowLocalPaths" => false,
		"returned" => "SCGI-REPLY",
		"sends" => 1,
		"trusted" => true,
		"payload" => "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<methodCall><methodName>load_start</methodName><params><param><value><string>http://example.test/x.torrent</string></value></param><param><value><string>d.custom1.set=label</string></value></param></params></methodCall>",
		"log" => array(
			"xmlrpc-proxy: trusted: load_start (2 params)",
		),
	),
	"a command taking two arguments keeps both, each trimmed" => array(
		"request" => "<?xml version=\"1.0\"?><methodCall><methodName>load.start</methodName><params><param><value><string></string></value></param><param><value><string>http://example.test/x.torrent</string></value></param><param><value><string>d.custom.set=chk-state, 7</string></value></param></params></methodCall>",
		"mode" => "sanitize",
		"enableLog" => true,
		"safeParams" => array(
			"d.custom1.set",
			"d.custom.set",
			"d.directory.set",
		),
		"allowLocalPaths" => false,
		"returned" => "SCGI-REPLY",
		"sends" => 1,
		"trusted" => true,
		"payload" => "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<methodCall><methodName>load.start</methodName><params><param><value><string></string></value></param><param><value><string>http://example.test/x.torrent</string></value></param><param><value><string>d.custom.set=\"chk-state\",\"7\"</string></value></param></params></methodCall>",
		"log" => array(
			"xmlrpc-proxy: trusted: load.start (3 params)",
		),
	),
	"quotes and backslashes in a value are escaped, not dropped" => array(
		"request" => "<?xml version=\"1.0\"?><methodCall><methodName>load.start</methodName><params><param><value><string></string></value></param><param><value><string>http://example.test/x.torrent</string></value></param><param><value><string>d.custom1.set=say &quot;hi&quot; \\ bye</string></value></param></params></methodCall>",
		"mode" => "sanitize",
		"enableLog" => true,
		"safeParams" => array(
			"d.custom1.set",
			"d.custom.set",
			"d.directory.set",
		),
		"allowLocalPaths" => false,
		"returned" => "SCGI-REPLY",
		"sends" => 1,
		"trusted" => true,
		"payload" => "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<methodCall><methodName>load.start</methodName><params><param><value><string></string></value></param><param><value><string>http://example.test/x.torrent</string></value></param><param><value><string>d.custom1.set=\"say \\\"hi\\\" \\\\ bye\"</string></value></param></params></methodCall>",
		"log" => array(
			"xmlrpc-proxy: trusted: load.start (3 params)",
		),
	),
	"an argument starting with \$ is dropped rather than quoted" => array(
		"request" => "<?xml version=\"1.0\"?><methodCall><methodName>load.start</methodName><params><param><value><string></string></value></param><param><value><string>http://example.test/x.torrent</string></value></param><param><value><string>d.custom1.set=\$execute.capture=/bin/hostname</string></value></param></params></methodCall>",
		"mode" => "sanitize",
		"enableLog" => true,
		"safeParams" => array(
			"d.custom1.set",
			"d.custom.set",
			"d.directory.set",
		),
		"allowLocalPaths" => false,
		"returned" => "SCGI-REPLY",
		"sends" => 1,
		"trusted" => true,
		"payload" => "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<methodCall><methodName>load.start</methodName><params><param><value><string></string></value></param><param><value><string>http://example.test/x.torrent</string></value></param></params></methodCall>",
		"log" => array(
			"xmlrpc-proxy: trusted: load.start (kept 2 params, stripped: d.custom1.set=\$execute.capture=/bin/hostname)",
		),
	),
	"a value the client quoted itself is dropped" => array(
		"request" => "<?xml version=\"1.0\"?><methodCall><methodName>load.start</methodName><params><param><value><string></string></value></param><param><value><string>http://example.test/x.torrent</string></value></param><param><value><string>d.custom1.set=&quot;Movies, Inc&quot;</string></value></param></params></methodCall>",
		"mode" => "sanitize",
		"enableLog" => true,
		"safeParams" => array(
			"d.custom1.set",
			"d.custom.set",
			"d.directory.set",
		),
		"allowLocalPaths" => false,
		"returned" => "SCGI-REPLY",
		"sends" => 1,
		"trusted" => true,
		"payload" => "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<methodCall><methodName>load.start</methodName><params><param><value><string></string></value></param><param><value><string>http://example.test/x.torrent</string></value></param></params></methodCall>",
		"log" => array(
			"xmlrpc-proxy: trusted: load.start (kept 2 params, stripped: d.custom1.set=\"Movies, Inc\")",
		),
	),
	"a long stripped value is truncated in the log" => array(
		"request" => "<?xml version=\"1.0\"?><methodCall><methodName>load.start</methodName><params><param><value><string></string></value></param><param><value><string>http://example.test/x.torrent</string></value></param><param><value><string>execute=AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA</string></value></param></params></methodCall>",
		"mode" => "sanitize",
		"enableLog" => true,
		"safeParams" => array(
			"d.custom1.set",
			"d.custom.set",
			"d.directory.set",
		),
		"allowLocalPaths" => false,
		"returned" => "SCGI-REPLY",
		"sends" => 1,
		"trusted" => true,
		"payload" => "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<methodCall><methodName>load.start</methodName><params><param><value><string></string></value></param><param><value><string>http://example.test/x.torrent</string></value></param></params></methodCall>",
		"log" => array(
			"xmlrpc-proxy: trusted: load.start (kept 2 params, stripped: execute=AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA...)",
		),
	),
	"a newline in a stripped value cannot forge a log line" => array(
		"request" => "<?xml version=\"1.0\"?><methodCall><methodName>load.start</methodName><params><param><value><string></string></value></param><param><value><string>http://example.test/x.torrent</string></value></param><param><value><string>execute=evil\nxmlrpc-proxy: trusted: forged</string></value></param></params></methodCall>",
		"mode" => "sanitize",
		"enableLog" => true,
		"safeParams" => array(
			"d.custom1.set",
			"d.custom.set",
			"d.directory.set",
		),
		"allowLocalPaths" => false,
		"returned" => "SCGI-REPLY",
		"sends" => 1,
		"trusted" => true,
		"payload" => "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<methodCall><methodName>load.start</methodName><params><param><value><string></string></value></param><param><value><string>http://example.test/x.torrent</string></value></param></params></methodCall>",
		"log" => array(
			"xmlrpc-proxy: trusted: load.start (kept 2 params, stripped: execute=evil xmlrpc-proxy: trusted: forged)",
		),
	),
	"an empty allowlist strips every command param" => array(
		"request" => "<?xml version=\"1.0\"?><methodCall><methodName>load.start</methodName><params><param><value><string></string></value></param><param><value><string>http://example.test/x.torrent</string></value></param><param><value><string>d.custom1.set=label</string></value></param></params></methodCall>",
		"mode" => "sanitize",
		"enableLog" => true,
		"safeParams" => array(),
		"allowLocalPaths" => false,
		"returned" => "SCGI-REPLY",
		"sends" => 1,
		"trusted" => true,
		"payload" => "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<methodCall><methodName>load.start</methodName><params><param><value><string></string></value></param><param><value><string>http://example.test/x.torrent</string></value></param></params></methodCall>",
		"log" => array(
			"xmlrpc-proxy: trusted: load.start (kept 2 params, stripped: d.custom1.set=label)",
		),
	),
	"a load call with no params at all is still rebuilt" => array(
		"request" => "<?xml version=\"1.0\"?><methodCall><methodName>load.start</methodName><params></params></methodCall>",
		"mode" => "sanitize",
		"enableLog" => true,
		"safeParams" => array(
			"d.custom1.set",
			"d.custom.set",
			"d.directory.set",
		),
		"allowLocalPaths" => false,
		"returned" => "SCGI-REPLY",
		"sends" => 1,
		"trusted" => true,
		"payload" => "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<methodCall><methodName>load.start</methodName><params></params></methodCall>",
		"log" => array(
			"xmlrpc-proxy: trusted: load.start (0 params)",
		),
	),
	"logging off changes what is logged and nothing else" => array(
		"request" => "<?xml version=\"1.0\"?><methodCall><methodName>load.start</methodName><params><param><value><string></string></value></param><param><value><string>http://example.test/x.torrent</string></value></param><param><value><string>execute=evil</string></value></param></params></methodCall>",
		"mode" => "sanitize",
		"enableLog" => false,
		"safeParams" => array(
			"d.custom1.set",
			"d.custom.set",
			"d.directory.set",
		),
		"allowLocalPaths" => false,
		"returned" => "SCGI-REPLY",
		"sends" => 1,
		"trusted" => true,
		"payload" => "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<methodCall><methodName>load.start</methodName><params><param><value><string></string></value></param><param><value><string>http://example.test/x.torrent</string></value></param></params></methodCall>",
		"log" => array(),
	),
	"logging off on the unknown-method path too" => array(
		"request" => "<?xml version=\"1.0\"?><methodCall><methodName>system.client_version</methodName><params></params></methodCall>",
		"mode" => "sanitize",
		"enableLog" => false,
		"safeParams" => array(
			"d.custom1.set",
			"d.custom.set",
			"d.directory.set",
		),
		"allowLocalPaths" => false,
		"returned" => "SCGI-REPLY",
		"sends" => 1,
		"trusted" => false,
		"payload" => "<?xml version=\"1.0\"?><methodCall><methodName>system.client_version</methodName><params></params></methodCall>",
		"log" => array(),
	),
	"a multicall of read commands is forwarded untouched and untrusted" => array(
		"request" => "<?xml version=\"1.0\"?><methodCall><methodName>d.multicall2</methodName><params><param><value><string></string></value></param><param><value><string>main</string></value></param><param><value><string>d.name=</string></value></param></params></methodCall>",
		"mode" => "sanitize",
		"enableLog" => true,
		"safeParams" => array(
			"d.custom1.set",
			"d.custom.set",
			"d.directory.set",
		),
		"allowLocalPaths" => false,
		"returned" => "SCGI-REPLY",
		"sends" => 1,
		"trusted" => false,
		"payload" => "<?xml version=\"1.0\"?><methodCall><methodName>d.multicall2</methodName><params><param><value><string></string></value></param><param><value><string>main</string></value></param><param><value><string>d.name=</string></value></param></params></methodCall>",
		"log" => array(
			"xmlrpc-proxy: untrusted: d.multicall2 (1 command parameters this side does not rebuild)",
		),
	),
	"a multicall whose commands are all allowed is rebuilt and trusted" => array(
		"request" => "<?xml version=\"1.0\"?><methodCall><methodName>d.multicall2</methodName><params><param><value><string></string></value></param><param><value><string>main</string></value></param><param><value><string>d.custom1.set=label</string></value></param></params></methodCall>",
		"mode" => "sanitize",
		"enableLog" => true,
		"safeParams" => array(
			"d.custom1.set",
			"d.custom.set",
			"d.directory.set",
		),
		"allowLocalPaths" => false,
		"returned" => "SCGI-REPLY",
		"sends" => 1,
		"trusted" => true,
		"payload" => "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<methodCall><methodName>d.multicall2</methodName><params><param><value><string></string></value></param><param><value><string>main</string></value></param><param><value><string>d.custom1.set=\"label\"</string></value></param></params></methodCall>",
		"log" => array(
			"xmlrpc-proxy: trusted: d.multicall2 (3 params)",
		),
	),
	"one unrebuildable command sends the whole multicall untouched" => array(
		"request" => "<?xml version=\"1.0\"?><methodCall><methodName>d.multicall2</methodName><params><param><value><string></string></value></param><param><value><string>main</string></value></param><param><value><string>d.custom1.set=label</string></value></param><param><value><string>d.name=</string></value></param></params></methodCall>",
		"mode" => "sanitize",
		"enableLog" => true,
		"safeParams" => array(
			"d.custom1.set",
			"d.custom.set",
			"d.directory.set",
		),
		"allowLocalPaths" => false,
		"returned" => "SCGI-REPLY",
		"sends" => 1,
		"trusted" => false,
		"payload" => "<?xml version=\"1.0\"?><methodCall><methodName>d.multicall2</methodName><params><param><value><string></string></value></param><param><value><string>main</string></value></param><param><value><string>d.custom1.set=label</string></value></param><param><value><string>d.name=</string></value></param></params></methodCall>",
		"log" => array(
			"xmlrpc-proxy: untrusted: d.multicall2 (1 command parameters this side does not rebuild)",
		),
	),
	"a multicall carrying execute.capture is forwarded untouched and untrusted" => array(
		"request" => "<?xml version=\"1.0\"?><methodCall><methodName>d.multicall2</methodName><params><param><value><string></string></value></param><param><value><string>main</string></value></param><param><value><string>execute.capture=/bin/sh</string></value></param></params></methodCall>",
		"mode" => "sanitize",
		"enableLog" => true,
		"safeParams" => array(
			"d.custom1.set",
			"d.custom.set",
			"d.directory.set",
		),
		"allowLocalPaths" => false,
		"returned" => null,
		"sends" => 0,
		"trusted" => null,
		"payload" => null,
		"log" => array(
			"xmlrpc-proxy: rejected (not allowed on this connection): d.multicall2 carrying execute.capture",
		),
	),
	"an allowed command with a \$ argument makes the multicall untrusted" => array(
		"request" => "<?xml version=\"1.0\"?><methodCall><methodName>d.multicall2</methodName><params><param><value><string></string></value></param><param><value><string>main</string></value></param><param><value><string>d.custom1.set=\$execute.capture=/bin/hostname</string></value></param></params></methodCall>",
		"mode" => "sanitize",
		"enableLog" => true,
		"safeParams" => array(
			"d.custom1.set",
			"d.custom.set",
			"d.directory.set",
		),
		"allowLocalPaths" => false,
		"returned" => "SCGI-REPLY",
		"sends" => 1,
		"trusted" => false,
		"payload" => "<?xml version=\"1.0\"?><methodCall><methodName>d.multicall2</methodName><params><param><value><string></string></value></param><param><value><string>main</string></value></param><param><value><string>d.custom1.set=\$execute.capture=/bin/hostname</string></value></param></params></methodCall>",
		"log" => array(
			"xmlrpc-proxy: untrusted: d.multicall2 (1 command parameters this side does not rebuild)",
		),
	),
	"a chained command stays inside the argument it was quoted into" => array(
		"request" => "<?xml version=\"1.0\"?><methodCall><methodName>d.multicall2</methodName><params><param><value><string></string></value></param><param><value><string>main</string></value></param><param><value><string>d.custom1.set=a;d.stop=</string></value></param></params></methodCall>",
		"mode" => "sanitize",
		"enableLog" => true,
		"safeParams" => array(
			"d.custom1.set",
			"d.custom.set",
			"d.directory.set",
		),
		"allowLocalPaths" => false,
		"returned" => "SCGI-REPLY",
		"sends" => 1,
		"trusted" => true,
		"payload" => "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<methodCall><methodName>d.multicall2</methodName><params><param><value><string></string></value></param><param><value><string>main</string></value></param><param><value><string>d.custom1.set=\"a;d.stop=\"</string></value></param></params></methodCall>",
		"log" => array(
			"xmlrpc-proxy: trusted: d.multicall2 (3 params)",
		),
	),
	"a multicall view name is data, never a command" => array(
		"request" => "<?xml version=\"1.0\"?><methodCall><methodName>d.multicall2</methodName><params><param><value><string></string></value></param><param><value><string>d.custom1.set=notacommand</string></value></param><param><value><string>d.custom1.set=label</string></value></param></params></methodCall>",
		"mode" => "sanitize",
		"enableLog" => true,
		"safeParams" => array(
			"d.custom1.set",
			"d.custom.set",
			"d.directory.set",
		),
		"allowLocalPaths" => false,
		"returned" => "SCGI-REPLY",
		"sends" => 1,
		"trusted" => true,
		"payload" => "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<methodCall><methodName>d.multicall2</methodName><params><param><value><string></string></value></param><param><value><string>d.custom1.set=notacommand</string></value></param><param><value><string>d.custom1.set=\"label\"</string></value></param></params></methodCall>",
		"log" => array(
			"xmlrpc-proxy: trusted: d.multicall2 (3 params)",
		),
	),
	"a data param that cannot be rebuilt makes the multicall untrusted" => array(
		"request" => "<?xml version=\"1.0\"?><methodCall><methodName>d.multicall2</methodName><params><param><value><int>1</int></value></param><param><value><string>main</string></value></param><param><value><string>d.custom1.set=label</string></value></param></params></methodCall>",
		"mode" => "sanitize",
		"enableLog" => true,
		"safeParams" => array(
			"d.custom1.set",
			"d.custom.set",
			"d.directory.set",
		),
		"allowLocalPaths" => false,
		"returned" => "SCGI-REPLY",
		"sends" => 1,
		"trusted" => false,
		"payload" => "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<methodCall><methodName>d.multicall2</methodName><params><param><value><int>1</int></value></param><param><value><string>main</string></value></param><param><value><string>d.custom1.set=\"label\"</string></value></param></params></methodCall>",
		"log" => array(
			"xmlrpc-proxy: untrusted (a parameter could not be rebuilt): d.multicall2 (3 params)",
		),
	),
	"d.multicall takes commands in the same position" => array(
		"request" => "<?xml version=\"1.0\"?><methodCall><methodName>d.multicall</methodName><params><param><value><string></string></value></param><param><value><string>main</string></value></param><param><value><string>d.custom1.set=label</string></value></param></params></methodCall>",
		"mode" => "sanitize",
		"enableLog" => true,
		"safeParams" => array(
			"d.custom1.set",
			"d.custom.set",
			"d.directory.set",
		),
		"allowLocalPaths" => false,
		"returned" => "SCGI-REPLY",
		"sends" => 1,
		"trusted" => true,
		"payload" => "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<methodCall><methodName>d.multicall</methodName><params><param><value><string></string></value></param><param><value><string>main</string></value></param><param><value><string>d.custom1.set=\"label\"</string></value></param></params></methodCall>",
		"log" => array(
			"xmlrpc-proxy: trusted: d.multicall (3 params)",
		),
	),
	"d.multicall.filtered takes commands in the same position" => array(
		"request" => "<?xml version=\"1.0\"?><methodCall><methodName>d.multicall.filtered</methodName><params><param><value><string></string></value></param><param><value><string>main</string></value></param><param><value><string>d.custom1.set=label</string></value></param></params></methodCall>",
		"mode" => "sanitize",
		"enableLog" => true,
		"safeParams" => array(
			"d.custom1.set",
			"d.custom.set",
			"d.directory.set",
		),
		"allowLocalPaths" => false,
		"returned" => "SCGI-REPLY",
		"sends" => 1,
		"trusted" => true,
		"payload" => "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<methodCall><methodName>d.multicall.filtered</methodName><params><param><value><string></string></value></param><param><value><string>main</string></value></param><param><value><string>d.custom1.set=\"label\"</string></value></param></params></methodCall>",
		"log" => array(
			"xmlrpc-proxy: trusted: d.multicall.filtered (3 params)",
		),
	),
	"t.multicall is command-carrying too" => array(
		"request" => "<?xml version=\"1.0\"?><methodCall><methodName>t.multicall</methodName><params><param><value><string>0123456789ABCDEF0123456789ABCDEF01234567</string></value></param><param><value><string></string></value></param><param><value><string>t.url=</string></value></param></params></methodCall>",
		"mode" => "sanitize",
		"enableLog" => true,
		"safeParams" => array(
			"d.custom1.set",
			"d.custom.set",
			"d.directory.set",
		),
		"allowLocalPaths" => false,
		"returned" => "SCGI-REPLY",
		"sends" => 1,
		"trusted" => false,
		"payload" => "<?xml version=\"1.0\"?><methodCall><methodName>t.multicall</methodName><params><param><value><string>0123456789ABCDEF0123456789ABCDEF01234567</string></value></param><param><value><string></string></value></param><param><value><string>t.url=</string></value></param></params></methodCall>",
		"log" => array(
			"xmlrpc-proxy: untrusted: t.multicall (1 command parameters this side does not rebuild)",
		),
	),
	"f.multicall is command-carrying too" => array(
		"request" => "<?xml version=\"1.0\"?><methodCall><methodName>f.multicall</methodName><params><param><value><string>0123456789ABCDEF0123456789ABCDEF01234567</string></value></param><param><value><string></string></value></param><param><value><string>f.path=</string></value></param></params></methodCall>",
		"mode" => "sanitize",
		"enableLog" => true,
		"safeParams" => array(
			"d.custom1.set",
			"d.custom.set",
			"d.directory.set",
		),
		"allowLocalPaths" => false,
		"returned" => "SCGI-REPLY",
		"sends" => 1,
		"trusted" => false,
		"payload" => "<?xml version=\"1.0\"?><methodCall><methodName>f.multicall</methodName><params><param><value><string>0123456789ABCDEF0123456789ABCDEF01234567</string></value></param><param><value><string></string></value></param><param><value><string>f.path=</string></value></param></params></methodCall>",
		"log" => array(
			"xmlrpc-proxy: untrusted: f.multicall (1 command parameters this side does not rebuild)",
		),
	),
	"p.multicall is command-carrying too" => array(
		"request" => "<?xml version=\"1.0\"?><methodCall><methodName>p.multicall</methodName><params><param><value><string>0123456789ABCDEF0123456789ABCDEF01234567</string></value></param><param><value><string></string></value></param><param><value><string>p.address=</string></value></param></params></methodCall>",
		"mode" => "sanitize",
		"enableLog" => true,
		"safeParams" => array(
			"d.custom1.set",
			"d.custom.set",
			"d.directory.set",
		),
		"allowLocalPaths" => false,
		"returned" => "SCGI-REPLY",
		"sends" => 1,
		"trusted" => false,
		"payload" => "<?xml version=\"1.0\"?><methodCall><methodName>p.multicall</methodName><params><param><value><string>0123456789ABCDEF0123456789ABCDEF01234567</string></value></param><param><value><string></string></value></param><param><value><string>p.address=</string></value></param></params></methodCall>",
		"log" => array(
			"xmlrpc-proxy: untrusted: p.multicall (1 command parameters this side does not rebuild)",
		),
	),
	"system.multicall is not one of them" => array(
		"request" => "<?xml version=\"1.0\"?><methodCall><methodName>system.multicall</methodName><params><param><value><string>x</string></value></param></params></methodCall>",
		"mode" => "sanitize",
		"enableLog" => true,
		"safeParams" => array(
			"d.custom1.set",
			"d.custom.set",
			"d.directory.set",
		),
		"allowLocalPaths" => false,
		"returned" => "SCGI-REPLY",
		"sends" => 1,
		"trusted" => false,
		"payload" => "<?xml version=\"1.0\"?><methodCall><methodName>system.multicall</methodName><params><param><value><string>x</string></value></param></params></methodCall>",
		"log" => array(
			"xmlrpc-proxy: untrusted: system.multicall",
		),
	),
	"load.start from a local path is rejected" => array(
		"request" => "<?xml version=\"1.0\"?><methodCall><methodName>load.start</methodName><params><param><value><string></string></value></param><param><value><string>/srv/watch/x.torrent</string></value></param></params></methodCall>",
		"mode" => "sanitize",
		"enableLog" => true,
		"safeParams" => array(
			"d.custom1.set",
			"d.custom.set",
			"d.directory.set",
		),
		"allowLocalPaths" => false,
		"returned" => null,
		"sends" => 0,
		"trusted" => null,
		"payload" => null,
		"log" => array(
			"xmlrpc-proxy: rejected (load from a local path): load.start /srv/watch/x.torrent",
		),
	),
	"load.normal from a local path is rejected" => array(
		"request" => "<?xml version=\"1.0\"?><methodCall><methodName>load.normal</methodName><params><param><value><string></string></value></param><param><value><string>/srv/watch/x.torrent</string></value></param></params></methodCall>",
		"mode" => "sanitize",
		"enableLog" => true,
		"safeParams" => array(
			"d.custom1.set",
			"d.custom.set",
			"d.directory.set",
		),
		"allowLocalPaths" => false,
		"returned" => null,
		"sends" => 0,
		"trusted" => null,
		"payload" => null,
		"log" => array(
			"xmlrpc-proxy: rejected (load from a local path): load.normal /srv/watch/x.torrent",
		),
	),
	"the 0.9.x name is rejected the same way" => array(
		"request" => "<?xml version=\"1.0\"?><methodCall><methodName>load_start</methodName><params><param><value><string></string></value></param><param><value><string>/srv/watch/x.torrent</string></value></param></params></methodCall>",
		"mode" => "sanitize",
		"enableLog" => true,
		"safeParams" => array(
			"d.custom1.set",
			"d.custom.set",
			"d.directory.set",
		),
		"allowLocalPaths" => false,
		"returned" => "SCGI-REPLY",
		"sends" => 1,
		"trusted" => true,
		"payload" => "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<methodCall><methodName>load_start</methodName><params><param><value><string></string></value></param><param><value><string>/srv/watch/x.torrent</string></value></param></params></methodCall>",
		"log" => array(
			"xmlrpc-proxy: trusted: load_start (2 params)",
		),
	),
	"a relative path is a local path too" => array(
		"request" => "<?xml version=\"1.0\"?><methodCall><methodName>load.start</methodName><params><param><value><string></string></value></param><param><value><string>watch/x.torrent</string></value></param></params></methodCall>",
		"mode" => "sanitize",
		"enableLog" => true,
		"safeParams" => array(
			"d.custom1.set",
			"d.custom.set",
			"d.directory.set",
		),
		"allowLocalPaths" => false,
		"returned" => null,
		"sends" => 0,
		"trusted" => null,
		"payload" => null,
		"log" => array(
			"xmlrpc-proxy: rejected (load from a local path): load.start watch/x.torrent",
		),
	),
	"a tilde path is a local path too" => array(
		"request" => "<?xml version=\"1.0\"?><methodCall><methodName>load.start</methodName><params><param><value><string></string></value></param><param><value><string>~/watch/x.torrent</string></value></param></params></methodCall>",
		"mode" => "sanitize",
		"enableLog" => true,
		"safeParams" => array(
			"d.custom1.set",
			"d.custom.set",
			"d.directory.set",
		),
		"allowLocalPaths" => false,
		"returned" => null,
		"sends" => 0,
		"trusted" => null,
		"payload" => null,
		"log" => array(
			"xmlrpc-proxy: rejected (load from a local path): load.start ~/watch/x.torrent",
		),
	),
	"an uppercase scheme is a local path to rtorrent, so it is rejected" => array(
		"request" => "<?xml version=\"1.0\"?><methodCall><methodName>load.start</methodName><params><param><value><string></string></value></param><param><value><string>HTTP://example.test/x.torrent</string></value></param></params></methodCall>",
		"mode" => "sanitize",
		"enableLog" => true,
		"safeParams" => array(
			"d.custom1.set",
			"d.custom.set",
			"d.directory.set",
		),
		"allowLocalPaths" => false,
		"returned" => null,
		"sends" => 0,
		"trusted" => null,
		"payload" => null,
		"log" => array(
			"xmlrpc-proxy: rejected (load from a local path): load.start HTTP://example.test/x.torrent",
		),
	),
	"magnet without the ? is a local path to rtorrent, so it is rejected" => array(
		"request" => "<?xml version=\"1.0\"?><methodCall><methodName>load.start</methodName><params><param><value><string></string></value></param><param><value><string>magnet:xt=urn:btih:abc</string></value></param></params></methodCall>",
		"mode" => "sanitize",
		"enableLog" => true,
		"safeParams" => array(
			"d.custom1.set",
			"d.custom.set",
			"d.directory.set",
		),
		"allowLocalPaths" => false,
		"returned" => null,
		"sends" => 0,
		"trusted" => null,
		"payload" => null,
		"log" => array(
			"xmlrpc-proxy: rejected (load from a local path): load.start magnet:xt=urn:btih:abc",
		),
	),
	"a base64 parameter is read as the URI it decodes to" => array(
		"request" => "<?xml version=\"1.0\"?><methodCall><methodName>load.start</methodName><params><param><value><string></string></value></param><param><value><base64>L3Nydi93YXRjaC94LnRvcnJlbnQ=</base64></value></param></params></methodCall>",
		"mode" => "sanitize",
		"enableLog" => true,
		"safeParams" => array(
			"d.custom1.set",
			"d.custom.set",
			"d.directory.set",
		),
		"allowLocalPaths" => false,
		"returned" => null,
		"sends" => 0,
		"trusted" => null,
		"payload" => null,
		"log" => array(
			"xmlrpc-proxy: rejected (load from a local path): load.start /srv/watch/x.torrent",
		),
	),
	"an ftp url is accepted, as rtorrent accepts it" => array(
		"request" => "<?xml version=\"1.0\"?><methodCall><methodName>load.start</methodName><params><param><value><string></string></value></param><param><value><string>ftp://example.test/x.torrent</string></value></param></params></methodCall>",
		"mode" => "sanitize",
		"enableLog" => true,
		"safeParams" => array(
			"d.custom1.set",
			"d.custom.set",
			"d.directory.set",
		),
		"allowLocalPaths" => false,
		"returned" => "SCGI-REPLY",
		"sends" => 1,
		"trusted" => true,
		"payload" => "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<methodCall><methodName>load.start</methodName><params><param><value><string></string></value></param><param><value><string>ftp://example.test/x.torrent</string></value></param></params></methodCall>",
		"log" => array(
			"xmlrpc-proxy: trusted: load.start (2 params)",
		),
	),
	"a magnet is accepted" => array(
		"request" => "<?xml version=\"1.0\"?><methodCall><methodName>load.start</methodName><params><param><value><string></string></value></param><param><value><string>magnet:?xt=urn:btih:abc</string></value></param></params></methodCall>",
		"mode" => "sanitize",
		"enableLog" => true,
		"safeParams" => array(
			"d.custom1.set",
			"d.custom.set",
			"d.directory.set",
		),
		"allowLocalPaths" => false,
		"returned" => "SCGI-REPLY",
		"sends" => 1,
		"trusted" => true,
		"payload" => "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<methodCall><methodName>load.start</methodName><params><param><value><string></string></value></param><param><value><string>magnet:?xt=urn:btih:abc</string></value></param></params></methodCall>",
		"log" => array(
			"xmlrpc-proxy: trusted: load.start (2 params)",
		),
	),
	"load.raw_start is unaffected \xE2\x80\x94 its parameter is the torrent, not a URI" => array(
		"request" => "<?xml version=\"1.0\"?><methodCall><methodName>load.raw_start</methodName><params><param><value><string></string></value></param><param><value><base64>Ynl0ZXMAyGJ5dGVzAMhieXRlcwDIYnl0ZXMAyGJ5dGVzAMhieXRlcwDIYnl0ZXMAyGJ5dGVzAMg=\n</base64></value></param></params></methodCall>",
		"mode" => "sanitize",
		"enableLog" => true,
		"safeParams" => array(
			"d.custom1.set",
			"d.custom.set",
			"d.directory.set",
		),
		"allowLocalPaths" => false,
		"returned" => "SCGI-REPLY",
		"sends" => 1,
		"trusted" => true,
		"payload" => "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<methodCall><methodName>load.raw_start</methodName><params><param><value><string></string></value></param><param><value><base64>Ynl0ZXMAyGJ5dGVzAMhieXRlcwDIYnl0ZXMAyGJ5dGVzAMhieXRlcwDIYnl0ZXMAyGJ5dGVzAMg=</base64></value></param></params></methodCall>",
		"log" => array(
			"xmlrpc-proxy: trusted: load.raw_start (2 params)",
		),
	),
	"a local path is allowed when the operator turns it on" => array(
		"request" => "<?xml version=\"1.0\"?><methodCall><methodName>load.start</methodName><params><param><value><string></string></value></param><param><value><string>/srv/watch/x.torrent</string></value></param></params></methodCall>",
		"mode" => "sanitize",
		"enableLog" => true,
		"safeParams" => array(
			"d.custom1.set",
			"d.custom.set",
			"d.directory.set",
		),
		"allowLocalPaths" => true,
		"returned" => "SCGI-REPLY",
		"sends" => 1,
		"trusted" => true,
		"payload" => "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<methodCall><methodName>load.start</methodName><params><param><value><string></string></value></param><param><value><string>/srv/watch/x.torrent</string></value></param></params></methodCall>",
		"log" => array(
			"xmlrpc-proxy: trusted: load.start (2 params)",
		),
	),
	"execute.capture is refused" => array(
		"request" => "<?xml version=\"1.0\"?><methodCall><methodName>execute.capture</methodName><params><param><value><string></string></value></param><param><value><string>/bin/sh</string></value></param></params></methodCall>",
		"mode" => "sanitize",
		"enableLog" => true,
		"safeParams" => array(
			"d.custom1.set",
			"d.custom.set",
			"d.directory.set",
		),
		"allowLocalPaths" => false,
		"returned" => null,
		"sends" => 0,
		"trusted" => null,
		"payload" => null,
		"log" => array(
			"xmlrpc-proxy: rejected (not allowed on this connection): execute.capture",
		),
	),
	"method.insert is refused" => array(
		"request" => "<?xml version=\"1.0\"?><methodCall><methodName>method.insert</methodName><params><param><value><string></string></value></param><param><value><string>evil</string></value></param></params></methodCall>",
		"mode" => "sanitize",
		"enableLog" => true,
		"safeParams" => array(
			"d.custom1.set",
			"d.custom.set",
			"d.directory.set",
		),
		"allowLocalPaths" => false,
		"returned" => null,
		"sends" => 0,
		"trusted" => null,
		"payload" => null,
		"log" => array(
			"xmlrpc-proxy: rejected (not allowed on this connection): method.insert",
		),
	),
	"the 0.9.8 spelling execute2 is refused by the same prefix" => array(
		"request" => "<?xml version=\"1.0\"?><methodCall><methodName>execute2</methodName><params><param><value><string>id</string></value></param></params></methodCall>",
		"mode" => "sanitize",
		"enableLog" => true,
		"safeParams" => array(
			"d.custom1.set",
			"d.custom.set",
			"d.directory.set",
		),
		"allowLocalPaths" => false,
		"returned" => null,
		"sends" => 0,
		"trusted" => null,
		"payload" => null,
		"log" => array(
			"xmlrpc-proxy: rejected (not allowed on this connection): execute2",
		),
	),
	"schedule_remove2 is refused by the same prefix" => array(
		"request" => "<?xml version=\"1.0\"?><methodCall><methodName>schedule_remove2</methodName><params><param><value><string>x</string></value></param></params></methodCall>",
		"mode" => "sanitize",
		"enableLog" => true,
		"safeParams" => array(
			"d.custom1.set",
			"d.custom.set",
			"d.directory.set",
		),
		"allowLocalPaths" => false,
		"returned" => null,
		"sends" => 0,
		"trusted" => null,
		"payload" => null,
		"log" => array(
			"xmlrpc-proxy: rejected (not allowed on this connection): schedule_remove2",
		),
	),
	"import is refused" => array(
		"request" => "<?xml version=\"1.0\"?><methodCall><methodName>import</methodName><params><param><value><string></string></value></param><param><value><string>/tmp/evil.rc</string></value></param></params></methodCall>",
		"mode" => "sanitize",
		"enableLog" => true,
		"safeParams" => array(
			"d.custom1.set",
			"d.custom.set",
			"d.directory.set",
		),
		"allowLocalPaths" => false,
		"returned" => null,
		"sends" => 0,
		"trusted" => null,
		"payload" => null,
		"log" => array(
			"xmlrpc-proxy: rejected (not allowed on this connection): import",
		),
	),
	"a multicall carrying a refused command is refused, not forwarded" => array(
		"request" => "<?xml version=\"1.0\"?><methodCall><methodName>d.multicall2</methodName><params><param><value><string></string></value></param><param><value><string>main</string></value></param><param><value><string>execute.capture=/bin/sh</string></value></param></params></methodCall>",
		"mode" => "sanitize",
		"enableLog" => true,
		"safeParams" => array(
			"d.custom1.set",
			"d.custom.set",
			"d.directory.set",
		),
		"allowLocalPaths" => false,
		"returned" => null,
		"sends" => 0,
		"trusted" => null,
		"payload" => null,
		"log" => array(
			"xmlrpc-proxy: rejected (not allowed on this connection): d.multicall2 carrying execute.capture",
		),
	),
	"system.multicall carrying a refused member is refused" => array(
		"request" => "<?xml version=\"1.0\"?><methodCall><methodName>system.multicall</methodName><params><param><value><array><data><value><struct><member><name>methodName</name><value><string>execute.capture</string></value></member><member><name>params</name><value><array><data><value><string></string></value></data></array></value></member></struct></value></data></array></value></param></params></methodCall>",
		"mode" => "sanitize",
		"enableLog" => true,
		"safeParams" => array(
			"d.custom1.set",
			"d.custom.set",
			"d.directory.set",
		),
		"allowLocalPaths" => false,
		"returned" => null,
		"sends" => 0,
		"trusted" => null,
		"payload" => null,
		"log" => array(
			"xmlrpc-proxy: rejected (not allowed on this connection): system.multicall carrying execute.capture",
		),
	),
	"system.multicall of harmless members is still forwarded untrusted" => array(
		"request" => "<?xml version=\"1.0\"?><methodCall><methodName>system.multicall</methodName><params><param><value><array><data><value><struct><member><name>methodName</name><value><string>d.name</string></value></member><member><name>params</name><value><array><data><value><string>0123456789ABCDEF0123456789ABCDEF01234567</string></value></data></array></value></member></struct></value></data></array></value></param></params></methodCall>",
		"mode" => "sanitize",
		"enableLog" => true,
		"safeParams" => array(
			"d.custom1.set",
			"d.custom.set",
			"d.directory.set",
		),
		"allowLocalPaths" => false,
		"returned" => "SCGI-REPLY",
		"sends" => 1,
		"trusted" => false,
		"payload" => "<?xml version=\"1.0\"?><methodCall><methodName>system.multicall</methodName><params><param><value><array><data><value><struct><member><name>methodName</name><value><string>d.name</string></value></member><member><name>params</name><value><array><data><value><string>0123456789ABCDEF0123456789ABCDEF01234567</string></value></data></array></value></member></struct></value></data></array></value></param></params></methodCall>",
		"log" => array(
			"xmlrpc-proxy: untrusted: system.multicall",
		),
	),
	"passthrough_unsafe is not subject to the refusal list" => array(
		"request" => "<?xml version=\"1.0\"?><methodCall><methodName>execute.capture</methodName><params><param><value><string></string></value></param><param><value><string>/bin/sh</string></value></param></params></methodCall>",
		"mode" => "passthrough_unsafe",
		"enableLog" => true,
		"safeParams" => array(
			"d.custom1.set",
			"d.custom.set",
			"d.directory.set",
		),
		"allowLocalPaths" => false,
		"returned" => "SCGI-REPLY",
		"sends" => 1,
		"trusted" => true,
		"payload" => "<?xml version=\"1.0\"?><methodCall><methodName>execute.capture</methodName><params><param><value><string></string></value></param><param><value><string>/bin/sh</string></value></param></params></methodCall>",
		"log" => array(
			"xmlrpc-proxy: passthrough (UNSAFE mode)",
		),
	),
	"d.start on one hash is elevated" => array(
		"request" => "<?xml version=\"1.0\"?><methodCall><methodName>d.start</methodName><params><param><value><string>0123456789ABCDEF0123456789ABCDEF01234567</string></value></param></params></methodCall>",
		"mode" => "sanitize",
		"enableLog" => true,
		"safeParams" => array(
			"d.custom1.set",
			"d.custom.set",
			"d.directory.set",
		),
		"allowLocalPaths" => false,
		"returned" => "SCGI-REPLY",
		"sends" => 1,
		"trusted" => true,
		"payload" => "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<methodCall><methodName>d.start</methodName><params><param><value><string>0123456789ABCDEF0123456789ABCDEF01234567</string></value></param></params></methodCall>",
		"log" => array(
			"xmlrpc-proxy: trusted: d.start (elevated)",
		),
	),
	"d.stop on one hash is elevated" => array(
		"request" => "<?xml version=\"1.0\"?><methodCall><methodName>d.stop</methodName><params><param><value><string>0123456789ABCDEF0123456789ABCDEF01234567</string></value></param></params></methodCall>",
		"mode" => "sanitize",
		"enableLog" => true,
		"safeParams" => array(
			"d.custom1.set",
			"d.custom.set",
			"d.directory.set",
		),
		"allowLocalPaths" => false,
		"returned" => "SCGI-REPLY",
		"sends" => 1,
		"trusted" => true,
		"payload" => "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<methodCall><methodName>d.stop</methodName><params><param><value><string>0123456789ABCDEF0123456789ABCDEF01234567</string></value></param></params></methodCall>",
		"log" => array(
			"xmlrpc-proxy: trusted: d.stop (elevated)",
		),
	),
	"d.open on one hash is elevated" => array(
		"request" => "<?xml version=\"1.0\"?><methodCall><methodName>d.open</methodName><params><param><value><string>0123456789ABCDEF0123456789ABCDEF01234567</string></value></param></params></methodCall>",
		"mode" => "sanitize",
		"enableLog" => true,
		"safeParams" => array(
			"d.custom1.set",
			"d.custom.set",
			"d.directory.set",
		),
		"allowLocalPaths" => false,
		"returned" => "SCGI-REPLY",
		"sends" => 1,
		"trusted" => true,
		"payload" => "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<methodCall><methodName>d.open</methodName><params><param><value><string>0123456789ABCDEF0123456789ABCDEF01234567</string></value></param></params></methodCall>",
		"log" => array(
			"xmlrpc-proxy: trusted: d.open (elevated)",
		),
	),
	"a label is elevated and the value is carried as data" => array(
		"request" => "<?xml version=\"1.0\"?><methodCall><methodName>d.custom1.set</methodName><params><param><value><string>0123456789ABCDEF0123456789ABCDEF01234567</string></value></param><param><value><string>Movies (2024)</string></value></param></params></methodCall>",
		"mode" => "sanitize",
		"enableLog" => true,
		"safeParams" => array(
			"d.custom1.set",
			"d.custom.set",
			"d.directory.set",
		),
		"allowLocalPaths" => false,
		"returned" => "SCGI-REPLY",
		"sends" => 1,
		"trusted" => true,
		"payload" => "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<methodCall><methodName>d.custom1.set</methodName><params><param><value><string>0123456789ABCDEF0123456789ABCDEF01234567</string></value></param><param><value><string>Movies (2024)</string></value></param></params></methodCall>",
		"log" => array(
			"xmlrpc-proxy: trusted: d.custom1.set (elevated)",
		),
	),
	"a \$ value on an elevated setter is data, not a command" => array(
		"request" => "<?xml version=\"1.0\"?><methodCall><methodName>d.custom1.set</methodName><params><param><value><string>0123456789ABCDEF0123456789ABCDEF01234567</string></value></param><param><value><string>\$execute.capture=/bin/hostname</string></value></param></params></methodCall>",
		"mode" => "sanitize",
		"enableLog" => true,
		"safeParams" => array(
			"d.custom1.set",
			"d.custom.set",
			"d.directory.set",
		),
		"allowLocalPaths" => false,
		"returned" => "SCGI-REPLY",
		"sends" => 1,
		"trusted" => true,
		"payload" => "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<methodCall><methodName>d.custom1.set</methodName><params><param><value><string>0123456789ABCDEF0123456789ABCDEF01234567</string></value></param><param><value><string>\$execute.capture=/bin/hostname</string></value></param></params></methodCall>",
		"log" => array(
			"xmlrpc-proxy: trusted: d.custom1.set (elevated)",
		),
	),
	"d.priority.set takes a hash and a number" => array(
		"request" => "<?xml version=\"1.0\"?><methodCall><methodName>d.priority.set</methodName><params><param><value><string>0123456789ABCDEF0123456789ABCDEF01234567</string></value></param><param><value><string>2</string></value></param></params></methodCall>",
		"mode" => "sanitize",
		"enableLog" => true,
		"safeParams" => array(
			"d.custom1.set",
			"d.custom.set",
			"d.directory.set",
		),
		"allowLocalPaths" => false,
		"returned" => "SCGI-REPLY",
		"sends" => 1,
		"trusted" => true,
		"payload" => "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<methodCall><methodName>d.priority.set</methodName><params><param><value><string>0123456789ABCDEF0123456789ABCDEF01234567</string></value></param><param><value><i8>2</i8></value></param></params></methodCall>",
		"log" => array(
			"xmlrpc-proxy: trusted: d.priority.set (elevated)",
		),
	),
	"d.delete_tied is elevated on a hash" => array(
		"request" => "<?xml version=\"1.0\"?><methodCall><methodName>d.delete_tied</methodName><params><param><value><string>0123456789ABCDEF0123456789ABCDEF01234567</string></value></param></params></methodCall>",
		"mode" => "sanitize",
		"enableLog" => true,
		"safeParams" => array(
			"d.custom1.set",
			"d.custom.set",
			"d.directory.set",
		),
		"allowLocalPaths" => false,
		"returned" => "SCGI-REPLY",
		"sends" => 1,
		"trusted" => true,
		"payload" => "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<methodCall><methodName>d.delete_tied</methodName><params><param><value><string>0123456789ABCDEF0123456789ABCDEF01234567</string></value></param></params></methodCall>",
		"log" => array(
			"xmlrpc-proxy: trusted: d.delete_tied (elevated)",
		),
	),
	"a hash-shaped argument is required" => array(
		"request" => "<?xml version=\"1.0\"?><methodCall><methodName>d.start</methodName><params><param><value><string>not-a-hash</string></value></param></params></methodCall>",
		"mode" => "sanitize",
		"enableLog" => true,
		"safeParams" => array(
			"d.custom1.set",
			"d.custom.set",
			"d.directory.set",
		),
		"allowLocalPaths" => false,
		"returned" => "SCGI-REPLY",
		"sends" => 1,
		"trusted" => false,
		"payload" => "<?xml version=\"1.0\"?><methodCall><methodName>d.start</methodName><params><param><value><string>not-a-hash</string></value></param></params></methodCall>",
		"log" => array(
			"xmlrpc-proxy: untrusted: d.start (arguments did not match the allowed shape)",
		),
	),
	"an elevated method with the wrong argument count is not elevated" => array(
		"request" => "<?xml version=\"1.0\"?><methodCall><methodName>d.start</methodName><params><param><value><string>0123456789ABCDEF0123456789ABCDEF01234567</string></value></param><param><value><string>extra</string></value></param></params></methodCall>",
		"mode" => "sanitize",
		"enableLog" => true,
		"safeParams" => array(
			"d.custom1.set",
			"d.custom.set",
			"d.directory.set",
		),
		"allowLocalPaths" => false,
		"returned" => "SCGI-REPLY",
		"sends" => 1,
		"trusted" => false,
		"payload" => "<?xml version=\"1.0\"?><methodCall><methodName>d.start</methodName><params><param><value><string>0123456789ABCDEF0123456789ABCDEF01234567</string></value></param><param><value><string>extra</string></value></param></params></methodCall>",
		"log" => array(
			"xmlrpc-proxy: untrusted: d.start (arguments did not match the allowed shape)",
		),
	),
	"the xmlrpc size limit is elevated but clamped" => array(
		"request" => "<?xml version=\"1.0\"?><methodCall><methodName>network.xmlrpc.size_limit.set</methodName><params><param><value><string></string></value></param><param><value><string>999999999</string></value></param></params></methodCall>",
		"mode" => "sanitize",
		"enableLog" => true,
		"safeParams" => array(
			"d.custom1.set",
			"d.custom.set",
			"d.directory.set",
		),
		"allowLocalPaths" => false,
		"returned" => "SCGI-REPLY",
		"sends" => 1,
		"trusted" => true,
		"payload" => "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<methodCall><methodName>network.xmlrpc.size_limit.set</methodName><params><param><value><string></string></value></param><param><value><i8>16777216</i8></value></param></params></methodCall>",
		"log" => array(
			"xmlrpc-proxy: trusted: network.xmlrpc.size_limit.set (elevated)",
		),
	),
	"a size under the ceiling is passed through" => array(
		"request" => "<?xml version=\"1.0\"?><methodCall><methodName>network.xmlrpc.size_limit.set</methodName><params><param><value><string></string></value></param><param><value><string>2097152</string></value></param></params></methodCall>",
		"mode" => "sanitize",
		"enableLog" => true,
		"safeParams" => array(
			"d.custom1.set",
			"d.custom.set",
			"d.directory.set",
		),
		"allowLocalPaths" => false,
		"returned" => "SCGI-REPLY",
		"sends" => 1,
		"trusted" => true,
		"payload" => "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<methodCall><methodName>network.xmlrpc.size_limit.set</methodName><params><param><value><string></string></value></param><param><value><i8>2097152</i8></value></param></params></methodCall>",
		"log" => array(
			"xmlrpc-proxy: trusted: network.xmlrpc.size_limit.set (elevated)",
		),
	),
);
